### ISSUE TITLE
Change in redirect behaviour

### ISSUE THREAD

**Issue by TheRealAgentK** [jcberquist/commandbox-lex#2]
`cdn.lucee.org` changes the behaviour from the previously used `extension.lucee.org` when passing the version required via URL.

See screenshot for more details. First two requests are the old (correct) behaviour and return .36 as requested.

Bottom three requests are the flow via `cdn`, where the version is being cut off in a redirect and will always fall back to latest.

![Screenshot from 2024-07-24 11:27:48](https://github.com/user-attachments/assets/2a84ed97-72bf-4a6f-9299-e44e8ee22459)

I think `commandbox-lex` should stick with using `extension.lucee.org` for that reason.

**Comment by jcberquist** [comment]
Huh, interesting. That doesn't seem to be the case for all extensions, but I see it is clearly happening with the EHCache extension. Can you confirm that https://extension.lucee.org is the "correct" place to go for listing official Lucee extensions?

**Comment by jcberquist** [comment]
A search of https://github.com/lucee/Lucee does seem to show that domain is hardcoded there as the extension source - so it looks like I should revert the last change. Thanks for raising the issue.
